mlflow:
  work_dir: 'D:/01_WORKSPACE/09_LSTM_torch/mlflow'
  uri: 'http://127.0.0.1:5000'
  run_name: 'seq_20'
  cfg_path: 'D:/01_WORKSPACE/09_LSTM_torch/config/config.yaml'
  log_ckp: 'D:/01_WORKSPACE/09_LSTM_torch/log/'
  artifact: 'D:/01_WORKSPACE/09_LSTM_torch/mlflow/'
dataset:
  ROOT: 'D:/01_WORKSPACE/09_LSTM_torch/dataset'
  fol_name: '20220727_072205_ex0'
  wave_intencity: 1.0
  add_shift: false
  wave_shift:
    - -10
    - 10
    - 0.1
  sequence_num: 500
  add_noise: false
  data_window: 1
  label_window: 1
  time_shift: 1
  total_wave_num: 3
  train_wave_num: 1
  val_wave_num: 1
  test_wave_num: 1
  shuffle: false
model:
  name: 'One2OneStateful'
  stateful: true
  input_size: 1
  lstm_input: 100
  hidden_size: 500
  output_size: 1
  num_layers: 1
  bidirectional: false
train:
  num_epochs: 500
  log_root: 'D:/01_WORKSPACE/09_LSTM_torch/log'
infer:
  weight_root: 'D:/01_WORKSPACE/09_LSTM_torch/log'
  weigth_folder: '20220727_072503'
  recursive: false
